### ISSUE TITLE
Inconsistent labeling log fold-change in heatmap

### ISSUE THREAD

**Issue by schmittst** [drpowell/degust#73]
Hi David, sorry for raising all those issues - I really like your tool and am currently playing around quite heavily with it. Thanks for making this, its really helpful!
I have another thing which looks like a issue to me - but might be that I just did not understand it correctly: When I select certain genes in the Volcano plot (e.g. those with high log-fold-change) I get  a heat-map below that gives a color-code labelled as "Heatmap log-fold-change" with a scaling that is inconsistent to what I see in the Volcano plot.
See an example attached: Here I selected genes in the Volcano with numbers clearly above 2 (log-fold-change). However, in the heat-map scaling they are more close to 0 (almost white). Is it really log-fold-change what is shown in the heatmap?
Thanks again for your great work!
![logFC](https://user-images.githubusercontent.com/19912701/77154536-2ff13200-6a9c-11ea-9d1e-533a763e3095.PNG)

**Comment by drpowell** [comment]
Thanks for the feedback on degust.

The discrepancy you are hitting is due to the counts being more heavily moderated for the heatmap.  By default, for the heatmap the counts have a constant of 10 added before calculating the fold-change - ie. `log(count+10)`.  I do this so that the very low expressed genes don't dominate the pattern in the heatmap.  Whereas the ma-plot, volcano-plot and parallel-coords plots all use a much lower moderation ie. `log(count + 0.5)`.  This seems sensible for the best defaults, but the discrepancy can be confusing.

The `+10` moderation is also used in the MDS plot so that lowly expressed genes don't drive the layout.  This can actually be controlled by going to the MDS plot and changing the `moderation` slider.  Although it is on the MDS page it controls moderation for both the MDS plot and the heatmap.
